name: Build and Deploy

on:
    push: 
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy:
        runs-on: "ubuntu-latest"
    
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          
        - name: Install 
          run: npm install
          
        - name: Build
          run: npm build
          
        - name: deploy
          uses: demurgos/ga-deploy-git@v1
          
          